jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    dependencies:
      pre:
        - sudo apt-get --reinstall install libept1.4.12
        - sudo apt-get install -y aptitude
        - sudo aptitude -y install imagemagick
        - sudo aptitude -y install libmagickcore-dev
        - sudo aptitude -y install libmagickwand-dev
    steps:
      - checkout
      - run: bundle install
      - run: ruby './test/circle_ci.rb' 